plugins { id 'com.android.application' }
android {
    namespace 'com.example.zuiyouantirecall'
    compileSdk 35
    defaultConfig { applicationId 'com.example.zuiyouantirecall'; minSdk 26; targetSdk 28; versionCode 18; versionName '0.18-media-recall' }
}
dependencies { compileOnly 'de.robv.android.xposed:api:82' }
